theme: jekyll-theme-midnight
title: Sample github pages site
description: Welcome to Data 104 Social Media Web Analytics
url:  https://rk-carter.github.io/Data104/
author: E. Uribe
plugins: 
 - jekyll-seo-tag
google_analytics: "UA-179013849-1"
