theme: jekyll-theme-midnight
title: rk-carter's Sample GitHub Page
description: Dedicated to Data 104 Social Media Web Analytics
url:  https://rk-carter.github.io/Data104/
author: R. K. Carter
plugins: 
 - jekyll-seo-tag
google_analytics: "UA-179013849-1"
